FROM ubus-builder

RUN apt-get update && apt-get install -y \
    clang \
    libclang-dev
    

USER user

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
    . $HOME/.cargo/env && \
    rustup install stable && \
    rustup default stable

# Set environment for Rust
ENV PATH="/home/user/.cargo/bin:${PATH}"

# Set working directory (inside the container)
WORKDIR /var/build
